apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
        - name: driver-service
          image: driver-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
            - containerPort: 9092
          env:
            - name: DB_URL
              value: "jdbc:postgresql://postgres:5432/lastmile"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: SERVER_PORT
              value: "8082"
            - name: GRPC_PORT
              value: "9092"
---
apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  selector:
    app: driver-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
    - name: grpc
      port: 9092
      targetPort: 9092
