apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      containers:
        - name: location-service
          image: location-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
            - containerPort: 9094
          env:
            - name: DB_URL
              value: "jdbc:postgresql://postgres:5432/lastmile"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: SERVER_PORT
              value: "8084"
            - name: GRPC_PORT
              value: "9094"
            - name: DRIVER_GRPC
              value: "static://driver-service:9092"
            - name: MATCHING_GRPC
              value: "static://matching-service:9097"
---
apiVersion: v1
kind: Service
metadata:
  name: location-service
spec:
  selector:
    app: location-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
    - name: grpc
      port: 9094
      targetPort: 9094
