apiVersion: apps/v1
kind: Deployment
metadata:
  name: rider-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rider-service
  template:
    metadata:
      labels:
        app: rider-service
    spec:
      containers:
        - name: rider-service
          image: rider-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
            - containerPort: 9093
          env:
            - name: DB_URL
              value: "jdbc:postgresql://postgres:5432/lastmile"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: SERVER_PORT
              value: "8083"
            - name: GRPC_PORT
              value: "9093"
            - name: MATCHING_GRPC
              value: "static://matching-service:9097"
---
apiVersion: v1
kind: Service
metadata:
  name: rider-service
spec:
  selector:
    app: rider-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
    - name: grpc
      port: 9093
      targetPort: 9093
