apiVersion: apps/v1
kind: Deployment
metadata:
  name: station-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: station-service
  template:
    metadata:
      labels:
        app: station-service
    spec:
      containers:
        - name: station-service
          image: station-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
            - containerPort: 9095
          env:
            - name: DB_URL
              value: "jdbc:postgresql://postgres:5432/lastmile"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: SERVER_PORT
              value: "8085"
            - name: GRPC_PORT
              value: "9095"
---
apiVersion: v1
kind: Service
metadata:
  name: station-service
spec:
  selector:
    app: station-service
  ports:
    - name: http
      port: 8085
      targetPort: 8085
    - name: grpc
      port: 9095
      targetPort: 9095
